# Generated by Django 5.1.5 on 2025-02-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carta", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carta",
            name="texto",
            field=models.TextField(max_length=5000),
        ),
    ]
