# Generated by Django 4.1.3 on 2025-02-07 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gestionada", "0001_initial"),
        ("carta", "0007_alter_carta_etiqueta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carta",
            name="etiqueta",
        ),
        migrations.AddField(
            model_name="carta",
            name="subdelegacion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestionada.subdelegacion",
            ),
        ),
    ]
